export const ProjectActionTypes = {
  SET_PROJECTS: "SET_PROJECTS",
  ADD_PROJECT: "ADD_PROJECT",
  DELETE_PROJECT: "DELETE_PROJECT",
  SET_PROJECT: "SET_PROJECT",
  REMOVE_SET_PROJECT: "REMOVE_SET_PROJECT",
};

export const TimeRangeActionTypes = {
  SET_TIME_RANGE: "SET_TIME_RANGE",
  UPDATE_TIME_RANGE: "UPDATE_TIME_RANGE",
  DELETE_TIME_RANGE: "DELETE_TIME_RANGE",
  ADD_TIME_RANGES: "ADD_TIME_RANGES",
};

export const UserActionTypes = {
  SET_USER: "SET_USER",
  REMOVE_SET_USER: "REMOVE_SET_USER",
};
